trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'andresorduz1test'
    organization: 'luisorduz'
    scannerMode: 'Other'


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'andresorduz1test'
    organization: 'luisorduz'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliSources: '.'
# Builds project and runs automated tests


- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    sonarQubeRunAnalysis: true
    goals: 'install'
# Maven

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
